version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: Europe/Prague
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase
    versions:
    - 8.2.1
    - 8.2.5
  - dependency-name: react-navigation
    versions:
    - 4.4.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
